setup(name='FILE-CONVERTER',
      version='1.0.0',
      description='CONVERT CSV FILE TO JASON FILE',
      long_description=long_description,
      url='https://github.com/salazar64/FILE-CONVERTER',
      author='KEATS SALAZAR',
      author_email='scientistsalazar.com',
      license='MIT',
      classifiers=['Development Status :: 5 - Production/Stable',
                   'Intended Audience :: Developers',
                   'Topic :: Software Development :: Widget Sets',
                   'Topic :: Software Development :: Libraries :: Python Modules',
                   'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
                   'Programming Language :: Python :: 3',
                   'Programming Language :: Python :: 3.4',
                   'Programming Language :: Python :: 3.5',
                   'Programming Language :: Python :: 3.6',
                   'Operating System :: OS Independent'],
      keywords=['tkinter']